projects:
  - name: The Distance
    environments:
      - name: Production
        databases:
          - name: thedistance-db
            plan: basic-256mb
            postgresMajorVersion: "16"
        services:
          - type: web
            name: thedistance-api
            runtime: python
            rootDir: appview
            buildCommand: uv sync
            startCommand: uv run start
            plan: free
            domains:
              - api.thedistance.app
            envVars:
              - key: DATABASE_URL
                fromDatabase:
                  name: thedistance-db
                  property: connectionString
              - key: APP_URL
                value: https://api.thedistance.app
              - key: FRONTEND_URL
                value: https://thedistance.app
              - key: SESSION_SECRET_KEY
                sync: false
              - key: CLIENT_SECRET_JWK
                sync: false
              - key: UVICORN_RELOAD
                value: "false"

          - type: worker
            name: thedistance-subscriber
            runtime: python
            rootDir: appview
            buildCommand: uv sync
            startCommand: uv run subscribe
            plan: starter
            envVars:
              - key: DATABASE_URL
                fromDatabase:
                  name: thedistance-db
                  property: connectionString

          - type: web
            name: thedistance-web
            runtime: static
            rootDir: web
            domains:
              - thedistance.app
            buildCommand: pnpm install && pnpm build
            staticPublishPath: _site
            routes:
              - type: rewrite
                source: /profile/*/activity/*
                destination: /profile/activity/index.html
              - type: rewrite
                source: /profile/*
                destination: /profile/index.html
              - type: rewrite
                source: /upload
                destination: /upload/index.html
              - type: rewrite
                source: /about
                destination: /about/index.html
